ARISTA-CONFIG-MAN-MIB::aristaCmdHistory:
  mib: ARISTA-CONFIG-MAN-MIB
  object: aristaCmdHistory
  discovery_attribute: aristaCmdHistoryRunningLastChanged
  attributes:
    aristaCmdHistoryRunningLastChanged:
      oid: .1.3.6.1.4.1.30065.3.9.1.1.1
      name: arista.config.running.last_chg
      syntax: TimeTicks
