ARISTA-CONFIG-COPY-MIB::aristaConfigCopyCommandEntry:
  mib: ARISTA-CONFIG-COPY-MIB
  object: aristaConfigCopyCommandEntry
  index:
    - type: OctetString
      oid: .1.3.6.1.4.1.30065.3.7.1.1.1
      name: arista.config.copy.name # aristaConfigCopyName
      syntax: DisplayString
    - type: Unsigned32
      oid: .1.3.6.1.4.1.30065.3.7.1.1.2
      name: arista.config.copy.id # aristaConfigCopyId
      syntax: UnsignedAsID
  discovery_attribute: aristaConfigCopySourceUri
  attributes:
    aristaConfigCopySourceUri:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.3
      name: arista.config.copy.src.uri
      syntax: DisplayString
    aristaConfigCopyDestUri:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.4
      name: arista.config.copy.dst.uri
      syntax: DisplayString
    aristaConfigCopyState:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.5
      name: arista.config.copy.state
      syntax: EnumInteger
    aristaConfigCopyTimeout:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.6
      name: arista.config.copy.timeout
      syntax: TicksSec
    aristaConfigCopyTimeStarted:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.7
      name: arista.config.copy.time.start
      syntax: DateAndTime
    aristaConfigCopyTimeCompleted:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.8
      name: arista.config.copy.time.end
      syntax: DateAndTime
    aristaConfigCopyFailureCause:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.9
      name: arista.config.copy.fail.cause
      syntax: EnumInteger
    aristaConfigCopyFailureMessage:
      oid: .1.3.6.1.4.1.30065.3.7.1.1.10
      name: arista.config.copy.fail.msg
      syntax: DisplayString
