- mapping: |-
    #!blobl
    root = this
    root.out.origin.agent.name = "CISCO-CONFIG-MAN-MIB"
- switch:
    - check: this.trap.SpecificTrap == 1
      processors:
        - label: cisco_config_man_event
          mapping: |-
            #!blobl
            root = this

            root.out.object.name = "ccmHistoryEventEntry.43"
            root.out.event.message = "Configuration Changed via " + this.trap.VarBinds.index(0).Value.enum_enrich(".1.3.6.1.4.1.9.9.43.1.1.6.1.3").string() + "  ( Source: " + this.trap.VarBinds.index(1).Value.enum_enrich(".1.3.6.1.4.1.9.9.43.1.1.6.1.4").string() + ", Destination: " + this.trap.VarBinds.index(2).Value.enum_enrich(".1.3.6.1.4.1.9.9.43.1.1.6.1.5").string() + " )"
            root.out.event.category.name = "Configuration Change"
            root.out.event.class.name = "SNMPTRAP-cisco-CISCO-CONFIG-MAN-MIB-ciscoConfigManEvent"
            root.out.event.id = "SNMPTRAP-cisco-CISCO-CONFIG-MAN-MIB-ciscoConfigManEvent"
            root.out.event.severity.code = 2
            root.out.event.severity.level = "Critical"

            root.out.cisco.ccmHistoryEventCommandSource = this.trap.VarBinds.index(0).Value.enum_enrich(".1.3.6.1.4.1.9.9.43.1.1.6.1.3")
            root.out.cisco.ccmHistoryEventConfigSource = this.trap.VarBinds.index(1).Value.enum_enrich(".1.3.6.1.4.1.9.9.43.1.1.6.1.4")
            root.out.cisco.ccmHistoryEventConfigDestination = this.trap.VarBinds.index(2).Value.enum_enrich(".1.3.6.1.4.1.9.9.43.1.1.6.1.5")
            root.out.cisco.ccmHistoryEventTerminalUser = this.trap.VarBinds.index(3).Value.snmp_v2_tc_display_string()
    - check: this.trap.SpecificTrap == 2
      processors:
        - label: ccm_clirunning_config_changed
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - check: this.trap.SpecificTrap == 3
      processors:
        - label: ccm_ctidrolled_over
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - processors:
        - label: default
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = "Unknown Trap"
