- mapping: |-
    #!blobl
    root = this
    root.out.origin.agent.name = "CISCO-CONFIG-COPY-MIB"
- switch:
    - check: this.trap.SpecificTrap == 1
      processors:
        - label: cc_copy_completion
          mapping: |-
            #!blobl
            root = this

            root.out.event.class.name = "SNMPTRAP-cisco-CISCO-CONFIG-COPY-MIB-ccCopyCompletion"
            root.out.event.id = "SNMPTRAP-cisco-CISCO-CONFIG-COPY-MIB-ccCopyCompletion"
            root.out.event.category.name = "Configuration Copy Status"
            root.out.object.name = "ccCopyEntry.96"

            root.out.cisco.ccCopyServerAddress = this.trap.VarBinds.index(0).Value
            root.out.cisco.ccCopyFileName = this.trap.VarBinds.index(1).Value.snmp_v2_tc_display_string()
            root.out.cisco.ccCopyState = this.trap.VarBinds.index(2).Value.enum_enrich(".1.3.6.1.4.1.9.9.96.1.1.1.1.10")
            root.out.cisco.ccCopyTimeStarted = this.trap.VarBinds.index(3).Value
            root.out.cisco.ccCopyTimeCompleted = this.trap.VarBinds.index(4).Value
            root.out.cisco.ccCopyFailCause = this.trap.VarBinds.index(5).Value.enum_enrich(".1.3.6.1.4.1.9.9.96.1.1.1.1.13")
        - label: cc_copy_completion_nested_switch
          switch:
            - check: this.trap.VarBinds.index(2).Value == 1
              processors:
                - label: cc_copy_completion_nested_switch_1
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Configuration Copy Waiting"
                    root.out.event.severity.code = 2
                    root.out.event.severity.level = "Critical"
            - check: this.trap.VarBinds.index(2).Value == 2
              processors:
                - label: cc_copy_completion_nested_switch_2
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.severity.code = 2
                    root.out.event.severity.level = "Critical"
                    root.out.event.message = "Configuration Copy Running"
            - check: this.trap.VarBinds.index(2).Value == 3
              processors:
                - label: cc_copy_completion_nested_switch_3
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Configuration Copy Successful"
                    root.out.event.severity.code = 1
                    root.out.event.severity.level = "Alert"
            - check: this.trap.VarBinds.index(2).Value == 4
              processors:
                - label: cc_copy_completion_nested_switch_4
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.severity.code = 3
                    root.out.event.severity.level = "Error"
                    root.out.event.message = "Configuration Copy Failed, " + this.trap.VarBinds.index(5).Value.enum_enrich(".1.3.6.1.4.1.9.9.96.1.1.1.1.13").string()
            - processors:
                - label: cc_copy_completion_nested_switch_default
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Configuration Copy Status Unknown"
                    root.out.event.severity.code = 2
                    root.out.event.severity.level = "Critical"
        - label: cc_copy_completion_after_switch
          mapping: |
            #!blobl
            root = this

            root.out.event.message = root.out.event.message + "  ( TFTP Server: " + this.trap.VarBinds.index(0).Value.string() + ", File: " + this.trap.VarBinds.index(1).Value.snmp_v2_tc_display_string().string() +  " )"
    - processors:
        - label: default
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = "Unknown Trap"
