- mapping: |-
    #!blobl
    root = this
    root.out.origin.agent.name = "CISCO-ES-STACK-MIB"
- switch:
    - check: this.trap.SpecificTrap == 1
      processors:
        - label: cisco_es_stack_cfg_change
          mapping: |-
            #!blobl
            root = this

            root.out.event.class.name = "SNMPTRAP-cisco-CISCO-ES-STACK-MIB-ciscoEsStackCfgChange"
            root.out.event.id = "SNMPTRAP-cisco-CISCO-ES-STACK-MIB-ciscoEsStackCfgChange"
            root.out.event.message = "Number of Switches in Stack Changed to $3
            root.out.event.severity.code = 2
            root.out.event.severity.level = "Critical"
            root.out.event.category.name = "Stack Configuration Change"
            root.out.object.name = ""

            root.out.cisco.ciscoEsNumSwitches = this.trap.VarBinds.index(0).Value
    - check: this.trap.SpecificTrap == 2
      processors:
        - label: cisco_es_stack_pro_stack_matrix_change
          mapping: |-
            #!blobl
            root = this

            root.out.object.name = ""
            root.out.event.class.name = "SNMPTRAP-cisco-CISCO-ES-STACK-MIB-ciscoEsStackProStackMatrixChange"
            root.out.event.id = "SNMPTRAP-cisco-CISCO-ES-STACK-MIB-ciscoEsStackProStackMatrixChange"
            root.out.event.category.name = "Stack Active Matrix Status"

            root.out.cisco.ciscoEsProStackMatrixStatus = this.trap.VarBinds.index(0).Value.enum_enrich(".1.3.6.1.4.1.9.5.14.1.1.12")
        - label: cisco_es_stack_pro_stack_matrix_change_nested_switch
          switch:
            - check: ' == 1'
              processors:
                - label: cisco_es_stack_pro_stack_matrix_change_nested_switch_1
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Active Matrix Module Switched to Primary"
                    root.out.event.severity.code = 1
                    root.out.event.severity.level = "Alert"
            - check: ' == 2'
              processors:
                - label: cisco_es_stack_pro_stack_matrix_change_nested_switch_2
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Active Matrix Module Switched to Secondary"
                    root.out.event.severity.code = 1
                    root.out.event.severity.level = "Alert"
            - check: ' == 3'
              processors:
                - label: cisco_es_stack_pro_stack_matrix_change_nested_switch_3
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Active Matrix Module Status Unknown"
                    root.out.event.severity.code = 2
                    root.out.event.severity.level = "Critical"
            - check: ' == 4'
              processors:
                - label: cisco_es_stack_pro_stack_matrix_change_nested_switch_4
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Active Matrix Module Failed"
                    root.out.event.severity.code = 4
                    root.out.event.severity.level = "Warning"
            - processors:
                - label: cisco_es_stack_pro_stack_matrix_change_nested_switch_default
                  mapping: |
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Active Matrix Module Status Unknown"
                    root.out.event.severity.code = 2
                    root.out.event.severity.level = "Critical"
        - label: cisco_es_stack_pro_stack_matrix_change_after_switch
          mapping: |+
            #!blobl
            root = this

    - processors:
        - label: default
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = "Unknown Trap"
