CISCO-CONFIG-COPY-MIB::ccCopyEntry:
  mib: CISCO-CONFIG-COPY-MIB
  object: ccCopyEntry
  index:
    - type: Unsigned32
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.1
      name: ccCopyIndex
      syntax: Unsigned32
  discovery_attribute: ccCopyProtocol
  attributes:
    ccCopyProtocol:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.2
      name: ccCopyProtocol
      syntax: EnumInteger
    ccCopySourceFileType:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.3
      name: ccCopySourceFileType
      syntax: EnumInteger
    ccCopyDestFileType:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.4
      name: ccCopyDestFileType
      syntax: EnumInteger
    ccCopyServerAddress:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.5
      name: ccCopyServerAddress
      syntax: IpAddressNoSuffix # IpAddress
    ccCopyFileName:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.6
      name: ccCopyFileName
      syntax: DisplayString
    ccCopyUserName:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.7
      name: ccCopyUserName
      syntax: DisplayString
    ccCopyUserPassword:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.8
      name: ccCopyUserPassword
      syntax: DisplayString
    ccCopyNotificationOnCompletion:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.9
      name: ccCopyNotificationOnCompletion
      syntax: TruthValue
    ccCopyState:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.10
      name: ccCopyState
      syntax: EnumInteger
    ccCopyTimeStarted:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.11
      name: ccCopyTimeStarted
      syntax: TimeStamp
    ccCopyTimeCompleted:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.12
      name: ccCopyTimeCompleted
      syntax: TimeStamp
    ccCopyFailCause:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.13
      name: ccCopyFailCause
      syntax: EnumInteger
#    ccCopyEntryRowStatus:
#      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.14
#      name: ccCopyEntryRowStatus
#      syntax: RowStatus
    ccCopyServerAddressType:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.15
      name: ccCopyServerAddressType
      syntax: EnumInteger
    ccCopyServerAddressRev1:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.16
      name: ccCopyServerAddressRev1
      syntax: IpAddressNoSuffix # InetAddress
    ccCopyVrfName:
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.17
      name: ccCopyVrfName
      syntax: TODO_OctetString # OctetString

CISCO-CONFIG-COPY-MIB::ccCopyErrorEntry:
  mib: CISCO-CONFIG-COPY-MIB
  object: ccCopyErrorEntry
  index:
    - type: Unsigned32
      oid: .1.3.6.1.4.1.9.9.96.1.1.1.1.1
      name: ccCopyIndex
      syntax: Unsigned32
    - type: Unsigned32
      oid: .1.3.6.1.4.1.9.9.96.1.1.2.1.1
      name: ccCopyErrorIndex
      syntax: Unsigned32
  discovery_attribute: ccCopyErrorDeviceIpAddressType
  attributes:
    ccCopyErrorDeviceIpAddressType:
      oid: .1.3.6.1.4.1.9.9.96.1.1.2.1.2
      name: ccCopyErrorDeviceIpAddressType
      syntax: EnumInteger
    ccCopyErrorDeviceIpAddress:
      oid: .1.3.6.1.4.1.9.9.96.1.1.2.1.3
      name: ccCopyErrorDeviceIpAddress
      syntax: IpAddressNoSuffix # InetAddress
    ccCopyErrorDeviceWWN:
      oid: .1.3.6.1.4.1.9.9.96.1.1.2.1.4
      name: ccCopyErrorDeviceWWN
      syntax: FcNameIdOrZero
    ccCopyErrorDescription:
      oid: .1.3.6.1.4.1.9.9.96.1.1.2.1.5
      name: ccCopyErrorDescription
      syntax: DisplayString # SnmpAdminString

