# CISCO-UNIFIED-COMPUTING-CONFIG-MIB::cucsConfigSorterEntry:
#   mib: CISCO-UNIFIED-COMPUTING-CONFIG-MIB
#   object: cucsConfigSorterEntry
#   index:
#     - type: Unsigned32
#       oid: .1.3.6.1.4.1.9.9.719.1.61.1.1.1
#       name: cisco.cucsConfigSorterInstanceId
#       syntax: UnsignedAsID
#   discovery_attribute: cucsConfigSorterDn
#   attributes:
#     cucsConfigSorterDn:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.1.1.2
#       name: cisco.cucsConfigSorterDn
#       syntax: DisplayString # CucsManagedObjectId
#     cucsConfigSorterRn:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.1.1.3
#       name: cisco.cucsConfigSorterRn
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigSorterDirection:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.1.1.4
#       name: cisco.cucsConfigSorterDirection
#       syntax: EnumInteger
#     cucsConfigSorterSortClass:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.1.1.5
#       name: cisco.cucsConfigSorterSortClass
#       syntax: EnumInteger
#     cucsConfigSorterSortProp:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.1.1.6
#       name: cisco.cucsConfigSorterSortProp
#       syntax: DisplayString # SnmpAdminString

# CISCO-UNIFIED-COMPUTING-CONFIG-MIB::cucsConfigImpactEntry:
#   mib: CISCO-UNIFIED-COMPUTING-CONFIG-MIB
#   object: cucsConfigImpactEntry
#   index:
#     - type: Unsigned32
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.1
#       name: cisco.cucsConfigImpactInstanceId
#       syntax: UnsignedAsID
#   discovery_attribute: cucsConfigImpactDn
#   attributes:
#     cucsConfigImpactDn:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.2
#       name: cisco.cucsConfigImpactDn
#       syntax: DisplayString # CucsManagedObjectId
#     cucsConfigImpactRn:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.3
#       name: cisco.cucsConfigImpactRn
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigImpactAffectedObj:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.4
#       name: cisco.cucsConfigImpactAffectedObj
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigImpactAffectedServer:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.5
#       name: cisco.cucsConfigImpactAffectedServer
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigImpactChanges:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.6
#       name: cisco.cucsConfigImpactChanges
#       syntax: EnumBitmap
#     cucsConfigImpactConfigIssues:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.7
#       name: cisco.cucsConfigImpactConfigIssues
#       syntax: EnumBitmap
#     cucsConfigImpactConfigQualifier:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.8
#       name: cisco.cucsConfigImpactConfigQualifier
#       syntax: EnumBitmap
#     cucsConfigImpactConfigState:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.9
#       name: cisco.cucsConfigImpactConfigState
#       syntax: EnumInteger
#     cucsConfigImpactDeploymentMode:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.10
#       name: cisco.cucsConfigImpactDeploymentMode
#       syntax: EnumInteger
#     cucsConfigImpactName:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.11
#       name: cisco.cucsConfigImpactName
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigImpactRebootRequired:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.12
#       name: cisco.cucsConfigImpactRebootRequired
#       syntax: TruthValue
#     cucsConfigImpactAffectedChassis:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.13
#       name: cisco.cucsConfigImpactAffectedChassis
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigImpactChassisConfigIssues:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.14
#       name: cisco.cucsConfigImpactChassisConfigIssues
#       syntax: EnumBitmap
#     cucsConfigImpactChassisConfigQualifier:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.15
#       name: cisco.cucsConfigImpactChassisConfigQualifier
#       syntax: EnumBitmap
#     cucsConfigImpactChassisConfigState:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.2.1.16
#       name: cisco.cucsConfigImpactChassisConfigState
#       syntax: EnumInteger

# CISCO-UNIFIED-COMPUTING-CONFIG-MIB::cucsConfigManagedEpImpactResponseEntry:
#   mib: CISCO-UNIFIED-COMPUTING-CONFIG-MIB
#   object: cucsConfigManagedEpImpactResponseEntry
#   index:
#     - type: Unsigned32
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.1
#       name: cisco.cucsConfigManagedEpImpactResponseInstanceId
#       syntax: UnsignedAsID
#   discovery_attribute: cucsConfigManagedEpImpactResponseDn
#   attributes:
#     cucsConfigManagedEpImpactResponseDn:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.2
#       name: cisco.cucsConfigManagedEpImpactResponseDn
#       syntax: DisplayString # CucsManagedObjectId
#     cucsConfigManagedEpImpactResponseRn:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.3
#       name: cisco.cucsConfigManagedEpImpactResponseRn
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigManagedEpImpactResponseAffectedServers:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.4
#       name: cisco.cucsConfigManagedEpImpactResponseAffectedServers
#       syntax: Gauge32
#     cucsConfigManagedEpImpactResponseAppConnectorId:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.5
#       name: cisco.cucsConfigManagedEpImpactResponseAppConnectorId
#       syntax: Gauge32
#     cucsConfigManagedEpImpactResponseEpName:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.6
#       name: cisco.cucsConfigManagedEpImpactResponseEpName
#       syntax: DisplayString # SnmpAdminString
#     cucsConfigManagedEpImpactResponseImpactAnalyzerId:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.7
#       name: cisco.cucsConfigManagedEpImpactResponseImpactAnalyzerId
#       syntax: DateAndTime
#     cucsConfigManagedEpImpactResponseRebootRequired:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.8
#       name: cisco.cucsConfigManagedEpImpactResponseRebootRequired
#       syntax: TruthValue
#     cucsConfigManagedEpImpactResponseSourceConnectorId:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.9
#       name: cisco.cucsConfigManagedEpImpactResponseSourceConnectorId
#       syntax: Gauge32
#     cucsConfigManagedEpImpactResponseState:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.10
#       name: cisco.cucsConfigManagedEpImpactResponseState
#       syntax: EnumInteger
#     cucsConfigManagedEpImpactResponseAffectedChassisCnt:
#       oid: .1.3.6.1.4.1.9.9.719.1.61.3.1.12
#       name: cisco.cucsConfigManagedEpImpactResponseAffectedChassisCnt
#       syntax: Gauge32
