CISCO-CONFIG-MAN-MIB::ccmHistory:
  mib: CISCO-CONFIG-MAN-MIB
  object: ccmHistory
  discovery_attribute: ccmHistoryRunningLastChanged
  attributes:
    ccmHistoryRunningLastChanged:
      oid: .1.3.6.1.4.1.9.9.43.1.1.1
      name: cisco.config.running.last_chg
      syntax: TimeTicks
      metric: counter
    ccmHistoryRunningLastSaved:
      oid: .1.3.6.1.4.1.9.9.43.1.1.2
      name: cisco.config.running.last_save
      syntax: TimeTicks
      metric: counter
    ccmHistoryStartupLastChanged:
      oid: .1.3.6.1.4.1.9.9.43.1.1.3
      name: cisco.config.startup.last_chg
      syntax: TimeTicks
      metric: counter
