# ccCopyState
.1.3.6.1.4.1.9.9.96.1.1.1.1.10:
  1: 'waiting' # waiting
  2: 'running' # running
  3: 'successful' # successful
  4: 'failed' # failed

# ccCopyFailCause
.1.3.6.1.4.1.9.9.96.1.1.1.1.13:
  1: 'unknown' # unknown
  2: 'bad file name' # badFileName
  3: 'timeout' # timeout
  4: 'no memory' # noMem
  5: 'no configuration' # noConfig
  6: 'unsupported protocol' # unsupportedProtocol
  7: 'configuration apply failed' # someConfigApplyFailed
  8: 'system not ready' # systemNotReady
  9: 'request aborted' # requestAborted
