# ccCopyProtocol
.1.3.6.1.4.1.9.9.96.1.1.1.1.2:
  1: tftp
  2: ftp
  3: rcp
  4: scp
  5: sftp

# ccCopySourceFileType
.1.3.6.1.4.1.9.9.96.1.1.1.1.3:
  1: networkFile
  2: iosFile
  3: startupConfig
  4: runningConfig
  5: terminal
  6: fabricStartupConfig

# ccCopyDestFileType
.1.3.6.1.4.1.9.9.96.1.1.1.1.4:
  1: networkFile
  2: iosFile
  3: startupConfig
  4: runningConfig
  5: terminal
  6: fabricStartupConfig

# ccCopyState
.1.3.6.1.4.1.9.9.96.1.1.1.1.10:
  1: waiting
  2: running
  3: successful
  4: failed

# ccCopyFailCause
.1.3.6.1.4.1.9.9.96.1.1.1.1.13:
  1: unknown
  2: badFileName
  3: timeout
  4: noMem
  5: noConfig
  6: unsupportedProtocol
  7: someConfigApplyFailed
  8: systemNotReady
  9: requestAborted

# ccCopyServerAddressType
.1.3.6.1.4.1.9.9.96.1.1.1.1.15:
  0: unknown
  1: ipv4
  2: ipv6
  3: ipv4z
  4: ipv6z
  16: dns

# ccCopyErrorDeviceIpAddressType
.1.3.6.1.4.1.9.9.96.1.1.2.1.2:
  0: unknown
  1: ipv4
  2: ipv6
  3: ipv4z
  4: ipv6z
  16: dns
