.1.3.6.1.4.1.9.9.96.1.1.1.1.10:
  1: waiting
  2: running
  3: successful
  4: failed

.1.3.6.1.4.1.9.9.96.1.1.1.1.13:
  1: unknown
  2: badFileName
  3: timeout
  4: noMem
  5: noConfig
  6: unsupportedProtocol
  7: someConfigApplyFailed
  8: systemNotReady
  9: requestAborted
