.1.3.6.1.4.1.9.9.43.1.1.6.1.3:
  1: 'CLI' # commandLine
  2: 'SNMP' # SNMP

.1.3.6.1.4.1.9.9.43.1.1.6.1.4:
  1: 'erase' # erase
  2: 'command source' # commandSource
  3: 'running' # running
  4: 'startup' # startup
  5: 'local' # local
  6: 'network TFTP' # networkTftp
  7: 'network RCP' # networkRcp
  8: 'network FTP' # networkFtp
  9: 'network SCP' # networkScp

.1.3.6.1.4.1.9.9.43.1.1.6.1.5:
  1: 'erase' # erase
  2: 'command source' # commandSource
  3: 'running' # running
  4: 'startup' # startup
  5: 'local' # local
  6: 'network TFTP' # networkTftp
  7: 'network RCP' # networkRcp
  8: 'network FTP' # networkFtp
  9: 'network SCP' # networkScp

.1.3.6.1.4.1.9.9.43.1.1.6.1.6:
  1: 'not-applicable' # notApplicable
  2: 'unknown' # unknown
  3: 'console' # console
  4: 'terminal' # terminal
  5: 'virtual' # virtual
  6: 'auxiliary' # auxiliary
