# ccapAppLoadState
.1.3.6.1.4.1.9.9.146.1.1.1.1.3:
  1: builtIn
  2: loading
  3: loaded
  4: loadFailed

# ccapAppLoadFailReason
.1.3.6.1.4.1.9.9.146.1.1.1.1.4:
  1: none
  2: other
  3: notFound
  4: timedOut
  5: noPermission
  6: badSignature
  7: noSpace

# ccapAppGblStatsLogging
.1.3.6.1.4.1.9.9.146.1.4.11:
  1: disable
  2: enable

# ccapAppGblEventLogging
.1.3.6.1.4.1.9.9.146.1.4.12:
  1: disable
  2: enable

# ccapAppGblEvtLogflush
.1.3.6.1.4.1.9.9.146.1.4.13:
  1: ftp

# ccapAppGblStatsClear
.1.3.6.1.4.1.9.9.146.1.4.14:
  1: clear

# ccapAppIntfGblStatsLogging
.1.3.6.1.4.1.9.9.146.1.6.1:
  1: disable
  2: enable

# ccapAppIntfGblEventLogging
.1.3.6.1.4.1.9.9.146.1.6.2:
  1: disable
  2: enable

# ccapAppIntfGblEvtLogFlush
.1.3.6.1.4.1.9.9.146.1.6.3:
  1: ftp

# ccapAppIntfGblStatsClear
.1.3.6.1.4.1.9.9.146.1.6.4:
  1: clearStats
  2: clearEventlog
  3: clear

# ccapAppIntfHTTPStats
.1.3.6.1.4.1.9.9.146.1.6.8.1.2:
  1: disable
  2: enable

# ccapAppIntfHTTPEvtLog
.1.3.6.1.4.1.9.9.146.1.6.8.1.3:
  1: disable
  2: enable

# ccapAppIntfRTSPStats
.1.3.6.1.4.1.9.9.146.1.6.9.1.2:
  1: disable
  2: enable

# ccapAppIntfRTSPEvtLog
.1.3.6.1.4.1.9.9.146.1.6.9.1.3:
  1: disable
  2: enable

# ccapAppIntfTFTPStats
.1.3.6.1.4.1.9.9.146.1.6.10.1.2:
  1: disable
  2: enable

# ccapAppIntfTFTPEvtLog
.1.3.6.1.4.1.9.9.146.1.6.10.1.3:
  1: disable
  2: enable

# ccapAppIntfSMTPStats
.1.3.6.1.4.1.9.9.146.1.6.20.1.2:
  1: disable
  2: enable

# ccapAppIntfSMTPEvtLog
.1.3.6.1.4.1.9.9.146.1.6.20.1.3:
  1: disable
  2: enable

# ccapAppIntfAAAMethodListStats
.1.3.6.1.4.1.9.9.146.1.6.21.1.2:
  1: disable
  2: enable

# ccapAppIntfAAAMethodListEvtLog
.1.3.6.1.4.1.9.9.146.1.6.21.1.3:
  1: disable
  2: enable

# ccapAppIntfASRStats
.1.3.6.1.4.1.9.9.146.1.6.22.1.2:
  1: disable
  2: enable

# ccapAppIntfASREvtLog
.1.3.6.1.4.1.9.9.146.1.6.22.1.3:
  1: disable
  2: enable

# ccapAppIntfTTSStats
.1.3.6.1.4.1.9.9.146.1.6.23.1.2:
  1: disable
  2: enable

# ccapAppIntfTTSEvtLog
.1.3.6.1.4.1.9.9.146.1.6.23.1.3:
  1: disable
  2: enable
