.1.3.6.1.4.1.9.9.43.1.1.6.1.3:
  1: commandLine
  2: SNMP

.1.3.6.1.4.1.9.9.43.1.1.6.1.4:
  1: erase
  2: commandSource
  3: running
  4: startup
  5: local
  6: networkTftp
  7: networkRcp
  8: networkFtp
  9: networkScp

.1.3.6.1.4.1.9.9.43.1.1.6.1.5:
  1: erase
  2: commandSource
  3: running
  4: startup
  5: local
  6: networkTftp
  7: networkRcp
  8: networkFtp
  9: networkScp

.1.3.6.1.4.1.9.9.43.1.1.6.1.6:
  1: notApplicable
  2: unknown
  3: console
  4: terminal
  5: virtual
  6: auxiliary
