HH3C-CONFIG-MAN-MIB::hh3cCfgLog:
  mib: HH3C-CONFIG-MAN-MIB
  object: hh3cCfgLog
  discovery_attribute: hh3cCfgRunModifiedLast
  attributes:
    hh3cCfgRunModifiedLast:
      oid: .1.3.6.1.4.1.25506.2.4.1.1.1
      name: hh3c.Cfg.RunModifiedLast
      syntax: TimeTicks
      metric: counter
    hh3cCfgRunSavedLast:
      oid: .1.3.6.1.4.1.25506.2.4.1.1.2
      name: hh3c.Cfg.RunSavedLast
      syntax: TimeTicks
      metric: counter
    hh3cCfgStartModifiedLast:
      oid: .1.3.6.1.4.1.25506.2.4.1.1.3
      name: hh3c.Cfg.StartModifiedLast
      syntax: TimeTicks
      metric: counter
    hh3cCfgLogLimitedEntries:
      oid: .1.3.6.1.4.1.25506.2.4.1.1.4
      name: hh3c.Cfg.Log.LimitedEntries
      syntax: Integer32
    hh3cCfgLogDeletedEntries:
      oid: .1.3.6.1.4.1.25506.2.4.1.1.5
      name: hh3c.Cfg.Log.DeletedEntries
      syntax: Counter32
      metric: counter
