# aristaConfigCopyState
.1.3.6.1.4.1.30065.3.7.1.1.5:
  0: 'inactive' # inactive
  1: 'scheduled' # scheduled
  2: 'running' # running
  3: 'completed' # completed
  4: 'failed' # failed

# aristaConfigCopyFailureCause
.1.3.6.1.4.1.30065.3.7.1.1.9:
  0: 'none' # none
  1: 'unknown' # unknown
  2: 'timeout' # timeout
