# cucsConfigImpactChanges
.1.3.6.1.4.1.9.9.719.1.61.2.1.6:
  0: serverIdentity
  1: storage
  2: networking
  3: vnicVhbaPlacement
  4: bootOrder
  5: serverAssignment
  6: operationalPolicies
  7: storageIdentity
  22: chassisIdentity
  25: chassisAssignment

# cucsConfigImpactConfigIssues
.1.3.6.1.4.1.9.9.719.1.61.2.1.7:
  0: insufficientResources
  1: vnicCapacity
  2: vhbaCapacity
  3: fcoeCapacity
  4: switchVirtualIfCapacity
  5: macAddressAssignment
  6: wwpnAssignment
  7: wwnnAssignment
  8: systemUuidAssignment
  9: bootOrderSanImagePath
  10: bootOrderPxe
  11: computeUndiscovered
  12: adaptorProtectedEthCapability
  13: adaptorFcoeCapability
  14: incompatibleNumberOfLocalDisks
  15: adaptorRequirement
  16: memoryRequirement
  17: processorRequirement
  18: serverPositionRequirement
  19: computeUnavailable
  20: wwnnDerivationFromVhba
  21: bootConfigurationInvalid
  22: connectionPlacement
  23: wwpnDerivationVirtualizedPort
  24: macDerivationVirtualizedPort
  25: qosPolicyInvalid
  26: vlanPortCapacity
  27: physicalRequirement
  28: destructiveLocalDiskConfig
  29: powerGroupRequirement
  30: migration
  31: incompatibleBiosImage
  32: incompatibleDiskTypes
  33: incompatibleRaidLevel
  34: invalidWwn
  35: insufficientPowerBudget
  36: bootipPolicyInvalid
  37: hostimgPolicyInvalid
  38: imgsecPolicyInvalid
  39: provsrvPolicyInvalid
  40: pinningInvalid
  41: iscsiConfig
  42: vnicNotHaReady
  43: iscsiOverlayVnic
  44: missingPrimaryVlan
  45: missingRaidKey
  46: iscsiBootInvalid
  47: vifResourcesOverprovisioned
  48: bootOrderIscsi
  49: iscsiVnicInitiatorName
  50: iscsiVnicInvalidVlan
  51: storagePathConfigurationError
  52: zoneCapacity
  53: iscsiInitiatorIpAddress
  54: vfcVnicPvlanConflict
  55: vnicVconProvisioningChange
  56: namedVlanInaccessible
  57: iscsiIncompatibleOffloadSetting
  58: nonInterruptFsmRunning
  59: pinningVlanMismatch
  60: vnicVlanAssignmentError
  61: resourceOwnershipConflict
  62: duplicateAddressConflict

# cucsConfigImpactConfigQualifier
.1.3.6.1.4.1.9.9.719.1.61.2.1.8:
  0: insufficientResources
  1: vnicCapacity
  2: vhbaCapacity
  3: fcoeCapacity
  4: switchVirtualIfCapacity
  5: macAddressAssignment
  6: wwpnAssignment
  7: wwnnAssignment
  8: systemUuidAssignment
  9: bootOrderSanImagePath
  10: bootOrderPxe
  11: computeUndiscovered
  12: adaptorProtectedEthCapability
  13: adaptorFcoeCapability
  14: incompatibleNumberOfLocalDisks
  15: adaptorRequirement
  16: memoryRequirement
  17: processorRequirement
  18: serverPositionRequirement
  19: computeUnavailable
  20: wwnnDerivationFromVhba
  21: bootConfigurationInvalid
  22: connectionPlacement
  23: wwpnDerivationVirtualizedPort
  24: macDerivationVirtualizedPort
  25: qosPolicyInvalid
  26: vlanPortCapacity
  27: physicalRequirement
  28: destructiveLocalDiskConfig
  29: powerGroupRequirement
  30: migration
  31: incompatibleBiosImage
  32: incompatibleDiskTypes
  33: incompatibleRaidLevel
  34: invalidWwn
  35: insufficientPowerBudget
  36: bootipPolicyInvalid
  37: hostimgPolicyInvalid
  38: imgsecPolicyInvalid
  39: provsrvPolicyInvalid
  40: pinningInvalid
  41: iscsiConfig
  42: vnicNotHaReady
  43: iscsiOverlayVnic
  44: missingPrimaryVlan
  45: missingRaidKey
  46: iscsiBootInvalid
  47: vifResourcesOverprovisioned
  48: bootOrderIscsi
  49: iscsiVnicInitiatorName
  50: iscsiVnicInvalidVlan
  51: storagePathConfigurationError
  52: zoneCapacity
  53: iscsiInitiatorIpAddress
  54: vfcVnicPvlanConflict
  55: vnicVconProvisioningChange
  56: namedVlanInaccessible
  57: iscsiIncompatibleOffloadSetting
  58: nonInterruptFsmRunning
  59: pinningVlanMismatch
  60: vnicVlanAssignmentError
  61: resourceOwnershipConflict
  62: duplicateAddressConflict

# cucsConfigImpactChassisConfigIssues
.1.3.6.1.4.1.9.9.719.1.61.2.1.14:
  0: insufficientResources
  1: chassisUndiscovered
  2: chassisUnavailable
  3: insufficientPowerBudget
  4: nonInterruptFsmRunning
  5: resourceOwnershipConflict
  6: missingFirmwareImage
  7: migration
  8: physicalRequirement
  9: invalidChassisPack
  10: chassisProfileNotSupported
  11: firmwareVersionMismatch
  12: computeConnUnsupportedCmcVersion
  13: computeSecondControllerUnsupportedCmcVersion
  15: chassisFeatureCapabilityMismatch
  16: chassisFeatureCapabilityMismatchNonFatal

# cucsConfigImpactChassisConfigQualifier
.1.3.6.1.4.1.9.9.719.1.61.2.1.15:
  0: insufficientResources
  1: chassisUndiscovered
  2: chassisUnavailable
  3: insufficientPowerBudget
  4: nonInterruptFsmRunning
  5: resourceOwnershipConflict
  6: missingFirmwareImage
  7: migration
  8: physicalRequirement
  9: invalidChassisPack
  10: chassisProfileNotSupported
  11: firmwareVersionMismatch
  12: computeConnUnsupportedCmcVersion
  13: computeSecondControllerUnsupportedCmcVersion
  15: chassisFeatureCapabilityMismatch
  16: chassisFeatureCapabilityMismatchNonFatal
