- mapping: |-
    #!blobl
    root = this
    root.out.origin.agent.name = "AGENTCONFIG-MIB"
- switch:
    - check: this.trap.SpecificTrap == 12
      processors:
        - label: event_pulsed
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - check: this.trap.SpecificTrap == 22
      processors:
        - label: agent_heart_beat
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - check: this.trap.SpecificTrap == 31
      processors:
        - label: agent_license_corrupt
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - check: this.trap.SpecificTrap == 32
      processors:
        - label: agent_license_invalid
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - check: this.trap.SpecificTrap == 33
      processors:
        - label: agent_license_expiry
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - check: this.trap.SpecificTrap == 55
      processors:
        - label: agent_authentication_failure
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - check: this.trap.SpecificTrap == 38
      processors:
        - label: agent_termination
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = ""
            root.out.event.id = ""
            root.out.event.message = ""
            root.out.object.name = ""
            root.out.event.class.name = ""

            root.out.event.severity.code = ""
            root.out.event.severity.level = ""
    - processors:
        - label: default
          mapping: |
            #!blobl,
            root = this
            root.out.event.category.name = "Unknown Trap"
