# icfSecurAuthAnyMgr
.1.3.6.1.4.1.11.2.14.4.2:
  1: 'enabled' # enabled
  2: 'disabled' # disabled

# icfAuthMgrRcvTraps
.1.3.6.1.4.1.11.2.14.4.3.1.4:
  1: 'enabled' # enabled
  2: 'disabled' # disabled

# icfSecurIntruderFlag
.1.3.6.1.4.1.11.2.14.4.4.1:
  1: 'valid' # valid
  2: 'invalid' # invalid

# icfCommunityReadView
.1.3.6.1.4.1.11.2.14.4.5.1.3:
  1: 'none' # none
  2: 'discovery' # discovery
  3: 'restricted' # restricted
  4: 'user' # user
  5: 'root' # root

# icfCommunityWriteView
.1.3.6.1.4.1.11.2.14.4.5.1.4:
  1: 'none' # none
  2: 'discovery' # discovery
  3: 'restricted' # restricted
  4: 'user' # user
  5: 'root' # root

# icfAuthMgrAddrType
.1.3.6.1.4.1.11.2.14.4.6.1.2:
  1: 'ip' # ip
  2: 'ipx' # ipx

# icfAuthIPMgrAccess
.1.3.6.1.4.1.11.2.14.4.7.1.4:
  1: 'operator' # operator
  2: 'manager' # manager

# icfAuthIPMgrAccessMethod
.1.3.6.1.4.1.11.2.14.4.7.1.10:
  1: 'all' # all
  2: 'ssh' # ssh
  3: 'telnet' # telnet
  4: 'web' # web
  5: 'snmp' # snmp
  6: 'tftp' # tftp
