# hpSntpConfigMode
.1.3.6.1.4.1.11.2.14.11.1.8.1.1:
  1: 'disabled' # disabled
  2: 'unicast' # unicast
  3: 'broadcast' # broadcast
  4: 'dhcp' # dhcp

# hpSntpAuthentication
.1.3.6.1.4.1.11.2.14.11.1.8.1.5:
  1: 'enabled' # enabled
  2: 'disabled' # disabled

# hpSntpAuthenticationKeyAuthMode
.1.3.6.1.4.1.11.2.14.11.1.8.1.6.1.2:
  1: 'none' # none
  2: 'md5' # md5

# hpTimeSyncMethod
.1.3.6.1.4.1.11.2.14.11.1.8.2.1:
  1: 'none' # none
  2: 'sntp' # sntp
  3: 'timep' # timep
  4: 'timepOrSntp' # timepOrSntp
  5: 'ntp' # ntp
