# hh3cCfgLogSrcCmd
.1.3.6.1.4.1.25506.2.4.1.1.7.1.3:
  1: 'cmdLine' # cmdLine
  2: 'snmp' # snmp
  3: 'other' # other

# hh3cCfgLogSrcData
.1.3.6.1.4.1.25506.2.4.1.1.7.1.4:
  1: 'erase' # erase
  2: 'runningData' # runningData
  3: 'commandSource' # commandSource
  4: 'startupData' # startupData
  5: 'local' # local
  6: 'netFtp' # netFtp
  7: 'hotPlugging' # hotPlugging

# hh3cCfgLogDesData
.1.3.6.1.4.1.25506.2.4.1.1.7.1.5:
  1: 'unknown' # unknown
  2: 'runningData' # runningData
  3: 'commandSource' # commandSource
  4: 'startupData' # startupData
  5: 'local' # local
  6: 'netFtp' # netFtp
  7: 'hotPlugging' # hotPlugging

# hh3cCfgLogTerminalType
.1.3.6.1.4.1.25506.2.4.1.1.7.1.6:
  1: 'notApplicable' # notApplicable
  2: 'unknown' # unknown
  3: 'console' # console
  4: 'terminal' # terminal
  5: 'virtual' # virtual
  6: 'auxiliary' # auxiliary

# hh3cCfgOperateType
.1.3.6.1.4.1.25506.2.4.1.2.4.1.2:
  1: 'running2Startup' # running2Startup
  2: 'startup2Running' # startup2Running
  3: 'running2Net' # running2Net
  4: 'net2Running' # net2Running
  5: 'net2Startup' # net2Startup
  6: 'startup2Net' # startup2Net
  7: 'running2File' # running2File
  8: 'file2Running' # file2Running

# hh3cCfgOperateProtocol
.1.3.6.1.4.1.25506.2.4.1.2.4.1.3:
  1: 'ftp' # ftp
  2: 'tftp' # tftp
  3: 'clusterftp' # clusterftp
  4: 'clustertftp' # clustertftp

# hh3cCfgOperateResultOpType
.1.3.6.1.4.1.25506.2.4.1.2.5.1.3:
  1: 'running2Startup' # running2Startup
  2: 'startup2Running' # startup2Running
  3: 'running2Net' # running2Net
  4: 'net2Running' # net2Running
  5: 'net2Startup' # net2Startup
  6: 'startup2Net' # startup2Net
  7: 'running2File' # running2File
  8: 'file2Running' # file2Running

# hh3cCfgOperateState
.1.3.6.1.4.1.25506.2.4.1.2.5.1.4:
  1: 'opInProgress' # opInProgress
  2: 'opSuccess' # opSuccess
  3: 'opInvalidOperation' # opInvalidOperation
  4: 'opInvalidProtocol' # opInvalidProtocol
  5: 'opInvalidSourceName' # opInvalidSourceName
  6: 'opInvalidDestName' # opInvalidDestName
  7: 'opInvalidServerAddress' # opInvalidServerAddress
  8: 'opDeviceBusy' # opDeviceBusy
  9: 'opDeviceOpenError' # opDeviceOpenError
  10: 'opDeviceError' # opDeviceError
  11: 'opDeviceNotProgrammable' # opDeviceNotProgrammable
  12: 'opDeviceFull' # opDeviceFull
  13: 'opFileOpenError' # opFileOpenError
  14: 'opFileTransferError' # opFileTransferError
  15: 'opFileChecksumError' # opFileChecksumError
  16: 'opNoMemory' # opNoMemory
  17: 'opAuthFail' # opAuthFail
  18: 'opTimeOut' # opTimeOut
  19: 'opUnknownFailure' # opUnknownFailure
  20: 'opInvalidConfigFile' # opInvalidConfigFile
  21: 'opSlaveFull' # opSlaveFull
  22: 'opCopyToSlaveFailure' # opCopyToSlaveFailure

# hh3cCfgExecuteResultOpType
.1.3.6.1.4.1.25506.2.4.1.2.6.2.1.3:
  1: 'running2Startup' # running2Startup
  2: 'startup2Running' # startup2Running
  3: 'running2Net' # running2Net
  4: 'net2Running' # net2Running
  5: 'net2Startup' # net2Startup
  6: 'startup2Net' # startup2Net
  7: 'running2File' # running2File
  8: 'file2Running' # file2Running

# hh3cCfgExecuteState
.1.3.6.1.4.1.25506.2.4.1.2.6.2.1.4:
  1: 'opInProgress' # opInProgress
  2: 'opSuccess' # opSuccess
  3: 'opInvalidOperation' # opInvalidOperation
  4: 'opInvalidProtocol' # opInvalidProtocol
  5: 'opInvalidSourceName' # opInvalidSourceName
  6: 'opInvalidDestName' # opInvalidDestName
  7: 'opInvalidServerAddress' # opInvalidServerAddress
  8: 'opDeviceBusy' # opDeviceBusy
  9: 'opDeviceOpenError' # opDeviceOpenError
  10: 'opDeviceError' # opDeviceError
  11: 'opDeviceNotProgrammable' # opDeviceNotProgrammable
  12: 'opDeviceFull' # opDeviceFull
  13: 'opFileOpenError' # opFileOpenError
  14: 'opFileTransferError' # opFileTransferError
  15: 'opFileChecksumError' # opFileChecksumError
  16: 'opNoMemory' # opNoMemory
  17: 'opAuthFail' # opAuthFail
  18: 'opTimeOut' # opTimeOut
  19: 'opUnknownFailure' # opUnknownFailure
  20: 'opInvalidConfigFile' # opInvalidConfigFile
  21: 'opSlaveFull' # opSlaveFull
  22: 'opCopyToSlaveFailure' # opCopyToSlaveFailure
