# HP-ICF-SECURITY::icfSecurAuthMgrEntry:
#   mib: HP-ICF-SECURITY
#   object: icfSecurAuthMgrEntry
#   index:
#     - type: Integer32
#       oid: .1.3.6.1.4.1.11.2.14.4.3.1.1
#       name: hp.icfAuthMgrIndex
#       syntax: IntegerAsID
#   discovery_attribute: icfAuthMgrIpAddress
#   attributes:
#     icfAuthMgrIpAddress:
#       oid: .1.3.6.1.4.1.11.2.14.4.3.1.2
#       name: hp.icfAuthMgrIpAddress
#       syntax: IpAddressNoSuffix
#     icfAuthMgrRcvTraps:
#       oid: .1.3.6.1.4.1.11.2.14.4.3.1.4
#       name: hp.icfAuthMgrRcvTraps
#       syntax: EnumInteger

HP-ICF-SECURITY::icfSecurIntruder:
  mib: HP-ICF-SECURITY
  object: icfSecurIntruder
  discovery_attribute: icfSecurIntruderFlag
  attributes:
    icfSecurIntruderFlag:
      oid: .1.3.6.1.4.1.11.2.14.4.4.1
      name: hp.icfSecurIntruderFlag
      syntax: EnumInteger
    icfSecurIntruderIpAddress:
      oid: .1.3.6.1.4.1.11.2.14.4.4.2
      name: hp.icfSecurIntruderIpAddress
      syntax: IpAddressNoSuffix
    icfSecurIntruderTime:
      oid: .1.3.6.1.4.1.11.2.14.4.4.4
      name: hp.icfSecurIntruderTime
      syntax: TimeTicks

# HP-ICF-SECURITY::icfCommunityEntry:
#   mib: HP-ICF-SECURITY
#   object: icfCommunityEntry
#   index:
#     - type: Integer32
#       oid: .1.3.6.1.4.1.11.2.14.4.5.1.1
#       name: hp.icfCommunityIndex
#       syntax: IntegerAsID
#   discovery_attribute: icfCommunityName
#   attributes:
#     icfCommunityName:
#       oid: .1.3.6.1.4.1.11.2.14.4.5.1.2
#       name: hp.icfCommunityName
#       syntax: OctetString
#     icfCommunityReadView:
#       oid: .1.3.6.1.4.1.11.2.14.4.5.1.3
#       name: hp.icfCommunityReadView
#       syntax: EnumInteger
#     icfCommunityWriteView:
#       oid: .1.3.6.1.4.1.11.2.14.4.5.1.4
#       name: hp.icfCommunityWriteView
#       syntax: EnumInteger

# HP-ICF-SECURITY::icfAuthMgrEntry:
#   mib: HP-ICF-SECURITY
#   object: icfAuthMgrEntry
#   index:
#     - type: Integer32
#       oid: .1.3.6.1.4.1.11.2.14.4.5.1.1
#       name: hp.icfCommunityIndex
#       syntax: IntegerAsID
#     - type: Integer32
#       oid: .1.3.6.1.4.1.11.2.14.4.6.1.1
#       name: hp.icfAuthMgrSubIndex
#       syntax: IntegerAsID
#   discovery_attribute: icfAuthMgrAddrType
#   attributes:
#     icfAuthMgrAddrType:
#       oid: .1.3.6.1.4.1.11.2.14.4.6.1.2
#       name: hp.icfAuthMgrAddrType
#       syntax: EnumInteger
#     icfAuthMgrAddress:
#       oid: .1.3.6.1.4.1.11.2.14.4.6.1.3
#       name: hp.icfAuthMgrAddress
#       syntax: OctetString
#     icfAuthMgrMask:
#       oid: .1.3.6.1.4.1.11.2.14.4.6.1.4
#       name: hp.icfAuthMgrMask
#       syntax: OctetString

# HP-ICF-SECURITY::icfAuthIPMgrEntry:
#   mib: HP-ICF-SECURITY
#   object: icfAuthIPMgrEntry
#   index:
#     - type: Integer32
#       oid: .1.3.6.1.4.1.11.2.14.4.7.1.1
#       name: hp.icfAuthIPMgrIndex
#       syntax: IntegerAsID
#   discovery_attribute: icfAuthIPMgrAddress
#   attributes:
#     icfAuthIPMgrAddress:
#       oid: .1.3.6.1.4.1.11.2.14.4.7.1.2
#       name: hp.icfAuthIPMgrAddress
#       syntax: IpAddressNoSuffix
#     icfAuthIPMgrMask:
#       oid: .1.3.6.1.4.1.11.2.14.4.7.1.3
#       name: hp.icfAuthIPMgrMask
#       syntax: IpAddressNoSuffix
#     icfAuthIPMgrAccess:
#       oid: .1.3.6.1.4.1.11.2.14.4.7.1.4
#       name: hp.icfAuthIPMgrAccess
#       syntax: EnumInteger
#     icfAuthIPMgrInetAddress:
#       oid: .1.3.6.1.4.1.11.2.14.4.7.1.7
#       name: hp.icfAuthIPMgrInetAddress
#       syntax: IpAddressNoSuffix # InetAddress
#     icfAuthIPMgrInetAddrMask:
#       oid: .1.3.6.1.4.1.11.2.14.4.7.1.9
#       name: hp.icfAuthIPMgrInetAddrMask
#       syntax: IpAddressNoSuffix # InetAddress
#     icfAuthIPMgrAccessMethod:
#       oid: .1.3.6.1.4.1.11.2.14.4.7.1.10
#       name: hp.icfAuthIPMgrAccessMethod
#       syntax: EnumInteger
