HP-SNTPclientConfiguration-MIB::hpSntpConfig:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpSntpConfig
  discovery_attribute: hpSntpConfigMode
  attributes:
    hpSntpConfigMode:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.1
      name: hpSntpConfigMode
      syntax: EnumInteger
    hpSntpConfigPollInterval:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.2
      name: hpSntpConfigPollInterval
      syntax: Integer32
      metric: gauge
    hpSntpAuthentication:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.5
      name: hpSntpAuthentication
      syntax: EnumInteger

HP-SNTPclientConfiguration-MIB::hpSntpServerEntry:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpSntpServerEntry
  index:
    - type: IpAddress
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.3.1.1
      name: hpSntpServerAddress
      syntax: IpAddressNoSuffix
  discovery_attribute: hpSntpServerVersion
  attributes:
    hpSntpServerVersion:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.3.1.2
      name: hpSntpServerVersion
      syntax: Integer32
      metric: gauge
    hpSntpServerPriority:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.3.1.3
      name: hpSntpServerPriority
      syntax: Integer32
      metric: gauge

HP-SNTPclientConfiguration-MIB::hpSntpInetServerEntry:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpSntpInetServerEntry
  index:
    - type: Integer32
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.1
      name: hpSntpInetServerPriority
      syntax: Integer32
    - type: Integer32
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.2
      name: hpSntpInetServerAddressType
      syntax: skip
    - type: OctetString
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.3
      name: hpSntpInetServerAddress
      syntax: IpAddressNoSuffix
  discovery_attribute: hpSntpInetServerVersion
  attributes:
    hpSntpInetServerVersion:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.4
      name: hpSntpInetServerVersion
      syntax: Integer32
      metric: gauge
    hpSntpInetServerIsOobm:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.6
      name: hpSntpInetServerIsOobm
      syntax: TruthValue
    hpSntpInetServerAuthKeyId:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.7
      name: hpSntpInetServerAuthKeyId
      syntax: UnsignedAsID

HP-SNTPclientConfiguration-MIB::hpSntpAuthenticationKeyEntry:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpSntpAuthenticationKeyEntry
  index:
    - type: Unsigned32
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.6.1.1
      name: hpSntpAuthenticationKeyId
      syntax: UnsignedAsID
  discovery_attribute: hpSntpAuthenticationKeyAuthMode
  attributes:
    hpSntpAuthenticationKeyAuthMode:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.6.1.2
      name: hpSntpAuthenticationKeyAuthMode
      syntax: EnumInteger
    hpSntpAuthenticationKeyValue:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.6.1.3
      name: hpSntpAuthenticationKeyValue
      syntax: OctetString
    hpSntpAuthenticationKeyTrusted:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.6.1.4
      name: hpSntpAuthenticationKeyTrusted
      syntax: TruthValue
    hpSntpAuthenticationKeyEncrypted:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.6.1.6
      name: hpSntpAuthenticationKeyEncrypted
      syntax: OctetString

HP-SNTPclientConfiguration-MIB::hpSntpServerStatisticsEntry:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpSntpServerStatisticsEntry
  index:
    - type: Integer32
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.1
      name: hpSntpInetServerPriority
      syntax: Integer32
    - type: Integer32
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.2
      name: hpSntpInetServerAddressType
      syntax: skip
    - type: OctetString
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.4.1.3
      name: hpSntpInetServerAddress
      syntax: IpAddressNoSuffix
  discovery_attribute: hpSntpServerStatisticsAuthFailedPkts
  attributes:
    hpSntpServerStatisticsAuthFailedPkts:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.7.1.1
      name: hpSntpServerStatisticsAuthFailedPkts
      syntax: Counter32
      metric: counter

HP-SNTPclientConfiguration-MIB::hpSntpBroadcastServerEntry:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpSntpBroadcastServerEntry
  index:
    - type: IpAddress
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.8.1.1
      name: hpSntpBroadcastServerAddress
      syntax: IpAddressNoSuffix
  discovery_attribute: hpSntpBroadcastServerStatisticsAuthFailedPkts
  attributes:
    hpSntpBroadcastServerStatisticsAuthFailedPkts:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.1.8.1.2
      name: hpSntpBroadcastServerStatisticsAuthFailedPkts
      syntax: Counter32
      metric: counter

HP-SNTPclientConfiguration-MIB::hpTimeSyncMethodMod:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpTimeSyncMethodMod
  discovery_attribute: hpTimeSyncMethod
  attributes:
    hpTimeSyncMethod:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.2.1
      name: hpTimeSyncMethod
      syntax: EnumInteger

HP-SNTPclientConfiguration-MIB::hpSntpStatistics:
  mib: HP-SNTPclientConfiguration-MIB
  object: hpSntpStatistics
  discovery_attribute: hpSntpStatsRcvdPkts
  attributes:
    hpSntpStatsRcvdPkts:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.4.1
      name: hpSntpStatsRcvdPkts
      syntax: Counter32
      metric: counter
    hpSntpStatsSentPkts:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.4.2
      name: hpSntpStatsSentPkts
      syntax: Counter32
      metric: counter
    hpSntpStatsDroppedPkts:
      oid: .1.3.6.1.4.1.11.2.14.11.1.8.4.3
      name: hpSntpStatsDroppedPkts
      syntax: Counter32
      metric: counter

