- mapping: |-
    #!blobl
    root = this
    root.out.origin.agent.name = "CISCO-TS-STACK-MIB"
- switch:
    - check: this.trap.SpecificTrap == 1
      processors:
        - label: cisco_ts_stack_cfg_change_variables
          mapping: |-
            #!blobl
            root = this

            root.out.cisco.sysName = this.trap.VarBinds.index(0).Value.snmp_display_string()
            root.out.cisco.sysLocation = this.trap.VarBinds.index(1).Value.snmp_display_string()
            root.out.cisco.ciscoTsNumSwitches = this.trap.VarBinds.index(2).Value
        - label: cisco_ts_stack_cfg_change_rules_1
          mapping: |-
            #!blobl
            root = this

            root.out.event.category.name = "Stack Configuration"
            root.out.object.name = ""
            root.out.event.message = "Switch Added or Removed from Stack"
    - check: this.trap.SpecificTrap == 2
      processors:
        - label: cisco_ts_stack_pro_stack_matrix_change_variables
          mapping: |-
            #!blobl
            root = this

            root.out.cisco.sysName = this.trap.VarBinds.index(0).Value.snmp_display_string()
            root.out.cisco.sysLocation = this.trap.VarBinds.index(1).Value.snmp_display_string()
            root.out.cisco.ciscoTsProStackMatrixStatus = this.trap.VarBinds.index(2).Value.enum_enrich(".1.3.6.1.4.1.9.5.32.1.1.13")
        - label: cisco_ts_stack_pro_stack_matrix_change_rules_1
          mapping: |-
            #!blobl
            root = this

            root.out.event.category.name = "Stack Matrix"
            root.out.object.name = ""
        - label: cisco_ts_stack_pro_stack_matrix_change_rules_2
          switch:
            - check: this.trap.VarBinds.index(2).Value == 1
              processors:
                - label: cisco_ts_stack_pro_stack_matrix_change_rules_2_1
                  mapping: |-
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Switched Over to Primary Matrix"
            - check: this.trap.VarBinds.index(2).Value == 2
              processors:
                - label: cisco_ts_stack_pro_stack_matrix_change_rules_2_2
                  mapping: |-
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Switched Over to Secondary Matrix"
            - check: this.trap.VarBinds.index(2).Value == 3
              processors:
                - label: cisco_ts_stack_pro_stack_matrix_change_rules_2_3
                  mapping: |-
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Not Connected to a Matrix"
            - check: this.trap.VarBinds.index(2).Value == 4
              processors:
                - label: cisco_ts_stack_pro_stack_matrix_change_rules_2_4
                  mapping: |-
                    #!blobl
                    root = this

                    root.out.event.message = "Stack Matrix Failed"
        - label: cisco_ts_stack_pro_stack_matrix_change_rules_3
          mapping: |
            #!blobl
            root = this
    - processors:
        - label: default
          mapping: |
            #!blobl
            root = this

            root.out.event.category.name = "Unknown Trap"
