name: CI
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go_checks:
    name: Go checks
    uses: elastiflow/gha-reusable/.github/workflows/reusable_go_checks.yml@v0
    with:
      unit_test_cmd: make test
      unit_test_report_coverage_cmd: make coverage

  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run SNMP validation
        run: make validate

  generate_release_cache:
    if: ${{ github.ref_name == 'main' }}
    permissions:
      id-token: write
      contents: read
      # uses: elastiflow/gha-reusable/.github/workflows/reusable_goreleaser.yml@v0
    uses: elastiflow/gha-reusable/.github/workflows/reusable_goreleaser.yml@v0
    with:
      binary: "snmp-validator"
      pkg_name: "netobserv-snmp-defs"
      pkg_description: "Definitions for the ElastiFlow Unified SNMP Collector."
      build_dockerfile: Dockerfile.gorel
      build_args: |
        "GORELEASER_ARGS=--snapshot --skip=validate,publish"
      gha_cache_enabled: true
    secrets:
      build_gpg_key: ${{ secrets.GPG_KEY }}
      build_gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
