name: Go checks

concurrency:
  group: go-checks-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go_checks:
    name: Go checks
    uses: ./.github/workflows/reusable_go_checks.yml
    with:
      go_version_file: "go.mod"
