on:
  workflow_call:
    inputs:
      gosec_args:
        type: string
        default: "-severity high -exclude-dir examples -exclude=G115 ./..."
        description: "gosec tool command line arguments"
      unit_test_runs-on:
        type: string
        default: ubuntu-latest
        description: "GHA runner for the Unit Test job (ubuntu-latest, ubuntu-latest-4c, ubuntu-latest-8c)"
      runs-on:
        type: string
        default: ubuntu-latest
        description: "GHA runner for the job (ubuntu-latest, ubuntu-latest-4c, ubuntu-latest-8c)"
      timeout-minutes:
        type: number
        default: 10
        description: "Job timeout in minutes"
      go_version_file:
        type: string
        default: 'go.mod'
        description: "Go version file to use"
      sonarcloud_run:
        type: boolean
        default: false
        description: "If true, run a SonarCloud scan after unit tests complete"
      sonarcloud_project_key:
        type: string
        default: ""
        description: "SonarCloud project key"
      sonarcloud_org:
        type: string
        default: "elastiflow"
        description: "SonarCloud organization"
    secrets:
      sonarcloud_token:
        required: false
        description: "SonarCloud token (required if sonarcloud_run is true)"

jobs:
  go-mod-tidy:
    name: 'go-mod-tidy'
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go_version_file }}
      - name: Run Tidy
        run: |
          find . -type f -name 'go.mod' | while read -r svc; do
            cd $(dirname "${svc}");
            echo "In $(pwd)";
            go mod tidy;
            cd -;
          done
          git diff --exit-code
  goimports:
    name: 'goimports'
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go_version_file }}
      - name: Run goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          goimports -l -w ./
          git diff --exit-code
  staticcheck:
    name: 'staticcheck'
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go_version_file }}
      - name: Run Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          find . -type f -name 'go.mod' | while read -r svc; do
            cd $(dirname "${svc}");
            echo "In $(pwd)";
            staticcheck ./...;
            cd -;
          done
  gosec:
    name: 'gosec'
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go_version_file }}
      - name: Security Scan
        uses: securego/gosec@v2.22.2
        with:
          args: ${{ inputs.gosec_args }}
  semgrep:
    name: 'semgrep scan'
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: semgrep scan
        run: semgrep scan --config auto --error
  unit_test:
    name: 'unit test'
    runs-on: ${{ inputs.unit_test_runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go_version_file }}
      - name: Run tests
        run: make test
      - name: Report coverage
        if: always()
        run: |
          make coverage
          COVERAGE=$(go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          COVERAGE_PASS=$(echo $COVERAGE 80 | awk '{ print ($1 >= $2) ? "true" : "false" }')
          if [ $COVERAGE_PASS = "false" ]; then
            echo "test coverage failed - expected >= 80 / actual = $COVERAGE"
            exit 1
          fi
          echo "coverage passed: $COVERAGE"
      - name: SonarCloud Scan
        if: ${{ inputs.sonarcloud_run }}
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonarcloud_project_key }}
            -Dsonar.organization=${{ inputs.sonarcloud_org }}
            -Dsonar.go.coverage.reportPaths=coverage.out
        env:
          SONAR_TOKEN: ${{ secrets.sonarcloud_token }}